// <auto-generated />
using DropdownDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DropdownDemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250414080441_database")]
    partial class Database // Renamed from 'database' to 'Database'
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DropdownDemo.Models.DesignationEntity", b =>
            {
                b.Property<int>("DesignationId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DesignationId"));

                b.Property<string>("DesignationName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("DesignationId");

                b.ToTable("Designation");
            });
#pragma warning restore 612, 618
        }
    }
}
